### ISSUE TITLE
[English] Need help about API Key

### ISSUE THREAD

**Issue by ghost** [Nam-Ki-Bok/FIFA-Online-TMI#1]
안녕하세요!
I am oversea web-developer( not korean). I'm doing some side-project which **need** **Fifa Online Nexon** api-key ( for study purpose).  I got problem while the nexon is required KR/CN Phone to authenication it. So i can't get sign up it ;(. Is there anyway to achive the API-Key?. Thanks you

**Comment by kiboook** [comment]
HELLO!
I heard that if you can't authenticate yourself, you won't get an API key 😭😭
But just in case, ask Nexon!
